# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0de8fe412206249bc57ea14b25a6045a3cc435b44e5b8cb8e0bcad6cd0f52db52c97bc0d4f13ad7f43de96f6c2ad4c013ea21e4a5b2a91c85babcc9cb6d34182
  AWS_BUCKET: citycoasting-dev
  AWS_ACCESS_KEY_ID: AKIAIHJIA4EMIHPLIL4Q
  AWS_SECRET_ACCESS_KEY: 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

test:
  secret_key_base: 82052271199488c34b15dfddee97b7341cfc39560b6302b4a9afd212ca92e216a4ab931a8ee3a47206886e8b5beee7e2f624137681a9d7fa17123e5a543433cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


